function [PPI, intervalOK, peakIdx, ampOutliers] = cleanPeakDetection(peakTimes,peakIdx,highpassedSignal)
% cleanPPI - Identifies artifacts but returns FULL list of peaks
% and a PPI vector where artifacts are NaNs. This prevents "merging" gaps.

if numel(peakTimes) < 2
    PPI = [];
    intervalOK = [];
    return
end

% 1. Calculate raw intervals (seconds)
PPI = diff(peakTimes);

% 2. find implausible intervals
upperBound = 20 * median(PPI,'omitnan');
lowerBound = median(PPI,'omitnan')/ 50;
intervalOK = find(PPI);
intervalNotOK = [];

if ~isempty(find(PPI>upperBound,1))
    intervalNotOK  = find(PPI>upperBound);
end
if ~isempty(find(PPI<lowerBound,1))
    intervalNotOK  =  sort([intervalNotOK; find(PPI<lowerBound)]);
end

if ~isempty(intervalNotOK)
    intervalOK(intervalNotOK) =[];
    intervalNotOK = intervalNotOK+1;
else
    intervalNotOK = [];
end

% make sure interval indices represent the peak after any interval
intervalOK = intervalOK +1;
intervalOK = [1; intervalOK];

% plot new peaks
hold on
plot(peakIdx(intervalOK),highpassedSignal(peakIdx(intervalOK)),'Marker','+')
if ~isempty(intervalNotOK)
    hold on
    plot(peakIdx(intervalNotOK),highpassedSignal(peakIdx(intervalNotOK)),'Marker','*')
end

% 3. find outliers in reference to inplausible peak amplitude in
%     reference to previous peak amplitudes. Some high peaks are
%     generated by tugs on the PPG because participants jerked or moved
%     their hand / finger. Since these are not necessarily wrongly
%     identified peaks with regards to timing, they will be kept in the
%     data. However, any peaks that are detected that are not real
%     peaks will be deleted here.
peakAmpDiff = diff(highpassedSignal(peakIdx));
upperBound  = (max(abs(highpassedSignal))-median(abs(highpassedSignal)))/2;
signalOK    = find(peakAmpDiff);
signalNotOK = [];
bigUpwardOutlier = [];

% find identified peaks that appear at amplitudes that are clearly too
% low while preserving peaks coming after large outliers due to
% movement.
if ~isempty(find(peakAmpDiff>upperBound,1))
    bigUpwardOutlier   = find(peakAmpDiff>upperBound);
    bigDownwardOutlier = find(peakAmpDiff<0-upperBound);

    if ~isempty(bigDownwardOutlier)
      if  any(peakAmpDiff(bigUpwardOutlier) > 2*median(highpassedSignal(peakIdx)))
        if numel(bigUpwardOutlier)>numel(bigDownwardOutlier)
            fillers = zeros(numel(bigUpwardOutlier)-numel(bigDownwardOutlier),1);
            bigDownwardOutlier = [bigDownwardOutlier;fillers];

        elseif numel(bigUpwardOutlier)<numel(bigDownwardOutlier)
            fillers = zeros(numel(bigDownwardOutlier)-numel(bigUpwardOutlier),1);
            bigUpwardOutlier = [bigUpwardOutlier;fillers];

        end
            consecutive = bigDownwardOutlier-bigUpwardOutlier;

            if any(consecutive ==1)
                signalNotOK = find(peakAmpDiff<0-upperBound);
                i = consecutive ==1;
                if ~isempty(i)
                    consecutiveOutlier = bigDownwardOutlier(i);
                    [~,idx] = intersect(signalNotOK,consecutiveOutlier);
                    signalNotOK(idx)=[];
                end
            else
                signalNotOK = bigDownwardOutlier;
            end
        else
            signalNotOK = bigDownwardOutlier;
        end
    end
end
if ~isempty(signalNotOK)
    signalNotOK(signalNotOK==0)=[];
    signalOK(signalNotOK) = [];
    signalNotOK = signalNotOK+1;
else
    signalNotOK =[];
end

signalOK = signalOK+1;
signalOK = [1; signalOK];
signalOK(end) = []; % delete last index because edges are prone to erroneous detection

% plot new peaks
hold on
plot(peakIdx(signalOK),highpassedSignal(peakIdx(signalOK)),'Marker','+');
if ~isempty(signalNotOK)
    hold on
    plot(peakIdx(signalNotOK),highpassedSignal(peakIdx(signalNotOK)),'Marker','*');
end

if ~isempty(intervalNotOK) && ~isempty(signalNotOK)
    legend({'filtered signal','identified peaks','peaks after interval outliers',...
        'peaks identified as interval outlier detection',...
        'peaks after amplitude outlier detection','peaks identified as amplitude outliers'});
elseif ~isempty(intervalNotOK)
    legend({'filtered signal','identified peaks','peaks after interval outliers',...
        'peaks identified as interval outlier detection','peaks after amplitude outlier detection'});
elseif ~isempty(signalNotOK)
    legend({'filtered signal','identified peaks','peaks after interval outliers',...
        'peaks after amplitude outlier detection','peaks identified as amplitude outliers'});
else
    legend({'filtered signal','identified peaks','peaks after interval outliers',...
        'peaks after amplitude outlier detection'});
end


% 5. REPLACE bad intervals with NaN (Do NOT remove peaks)
% replace PPIs and peakIds after an outlier interval with NaN
peakOK = intersect(intervalOK,signalOK);
PPI(~peakOK) = NaN;
peakIdx     = peakIdx(peakOK);
ampOutliers = signalNotOK;
end